//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KJFramework.Platform.Deploy.Maintenance.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KJFramework.Platform.Deploy.Maintenance.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting regist to remote management node #Address : .
        /// </summary>
        internal static string MaintenanceDynamicDomainService_Regist_Starting_regist_to_remote_management_node__Address___ {
            get {
                return ResourceManager.GetString("MaintenanceDynamicDomainService_Regist_Starting_regist_to_remote_management_node_" +
                        "_Address___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to management node #Address : .
        /// </summary>
        internal static string MaintenanceDynamicDomainService_Start_Connecting_to_management_node__Address___ {
            get {
                return ResourceManager.GetString("MaintenanceDynamicDomainService_Start_Connecting_to_management_node__Address___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing protocol stack......
        /// </summary>
        internal static string MaintenanceDynamicDomainService_Start_Initializing_protocol_stack_____ {
            get {
                return ResourceManager.GetString("MaintenanceDynamicDomainService_Start_Initializing_protocol_stack_____", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing task scheduler.......
        /// </summary>
        internal static string MaintenanceDynamicDomainService_Start_Initializing_task_scheduler______ {
            get {
                return ResourceManager.GetString("MaintenanceDynamicDomainService_Start_Initializing_task_scheduler______", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing network for management connection......
        /// </summary>
        internal static string MaintenanceDynamicDomainService_Start_Preparing_network_for_management_connection_____ {
            get {
                return ResourceManager.GetString("MaintenanceDynamicDomainService_Start_Preparing_network_for_management_connection" +
                        "_____", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading configurations.......
        /// </summary>
        internal static string MaintenanceDynamicDomainService_Start_Reading_configurations______ {
            get {
                return ResourceManager.GetString("MaintenanceDynamicDomainService_Start_Reading_configurations______", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regist funtion node in task scheduler.......
        /// </summary>
        internal static string MaintenanceDynamicDomainService_Start_Regist_funtion_node_in_task_scheduler______ {
            get {
                return ResourceManager.GetString("MaintenanceDynamicDomainService_Start_Regist_funtion_node_in_task_scheduler______" +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regist network node in task scheduler.......
        /// </summary>
        internal static string MaintenanceDynamicDomainService_Start_Regist_network_node_in_task_scheduler______ {
            get {
                return ResourceManager.GetString("MaintenanceDynamicDomainService_Start_Regist_network_node_in_task_scheduler______" +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting task scheduler.......
        /// </summary>
        internal static string MaintenanceDynamicDomainService_Start_Starting_task_scheduler______ {
            get {
                return ResourceManager.GetString("MaintenanceDynamicDomainService_Start_Starting_task_scheduler______", resourceCulture);
            }
        }
    }
}
